name: 'Android Build Release'
run-name: 'Android Build Release'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL_STAGING: ${{ secrets.BASE_URL_STAGING }}
      BASE_URL_PRODUCTION: ${{ secrets.BASE_URL_PRODUCTION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Make Gradle wrapper executable
        run: |
          cd android
          chmod +x gradlew

      - name: Generate Codegen Artifacts
        run: |
          cd android
          # This command triggers the necessary code generation.
          node ../node_modules/react-native/scripts/generate-codegen-artifacts.js \
          --path ../ \
          --outputPath ../android/app/build/generated/source/codegen/

      - name: Build application
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
