name: release-bundle
on:
  workflow_dispatch:
  # push:
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Make Gradle wrapper executable
        run: |
          cd android
          chmod +x gradlew

      - name: Build Android bundle
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 3