name: cacheless-debug-apk
on:
  workflow_dispatch:
  # push:
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository 
        uses: actions/checkout@v2

      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.0'

      - name: Set up our JDK environment 
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 19

      - name: Install dependencies
        run: yarn

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate Offline Bundle
        run: yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

      - name: Clean Gradle
        run: |
          cd android && ./gradlew clean && cd ..

      - name: Clear Gradle Cache
        run: |
          rm -rf /home/runner/.gradle/

      - name: Generate Debug APK
        run: |
          cd android && ./gradlew assembleDebug && cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk